apiVersion: apps/v1
kind: Deployment
metadata:
   name: authapi
spec:
  selector:
    matchlabels:
      app: authapi
  replica: 2
  strategy:
    rollingUpdate:
      maxsurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
        - name: authapi
          image: tcyprien/auth_api
          imagePullPolicy: Always
          ports:
            - containerPoprt: 8080
